/*
 * Style-guide preview. Generated by /e25-style-gen.
 *
 * Renders every token, type style, and button variant produced from the Figma
 * style guide so you can eyeball parity against the source. This route is a QA
 * aid — safe to delete once the style guide is verified.
 *
 * The skill fills the arrays/sections below from the parsed Figma. Swatches use
 * the generated Tailwind color utilities (e.g. `bg-primary-1`); type rows apply
 * the generated typography classes (e.g. `.title-1`); buttons apply `.btn`
 * variant classes. Keep everything class-driven so the preview exercises the
 * real style guide rather than re-declaring values.
 */

import type { ReactNode } from "react";

type Swatch = { name: string; className: string; hex: string };
type TypeRow = { name: string; className: string; spec: string };

// TODO(e25-style-gen): populate from the Figma "Colors" sections.
const COLORS: Swatch[] = [];

// TODO(e25-style-gen): populate from the Figma "Typography" section.
const TYPE_SCALE: TypeRow[] = [];

// TODO(e25-style-gen): populate variant class names from the Figma "Buttons" section.
const BUTTON_VARIANTS: string[] = [];

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="mx-auto w-full max-w-[1120px] px-6 py-12">
      <h2 className="mb-6 text-2xl font-semibold">{title}</h2>
      {children}
    </section>
  );
}

export default function StyleGuidePage() {
  return (
    <main className="min-h-screen">
      <header className="mx-auto w-full max-w-[1120px] px-6 pt-16 pb-4">
        <h1 className="text-4xl font-bold">Style Guide</h1>
        <p className="mt-2 opacity-70">Generated from Figma by /e25-style-gen.</p>
      </header>

      <Section title="Colors">
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-5">
          {COLORS.map((c) => (
            <div key={c.name} className="rounded-lg border border-black/10 overflow-hidden">
              <div className={`h-24 w-full ${c.className}`} />
              <div className="p-3 text-sm">
                <div className="font-medium">{c.name}</div>
                <div className="opacity-60">{c.hex}</div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Typography">
        <div className="flex flex-col gap-8">
          {TYPE_SCALE.map((t) => (
            <div key={t.name} className="border-b border-black/10 pb-6">
              <div className="mb-2 text-xs uppercase tracking-wide opacity-50">
                {t.name} — {t.spec}
              </div>
              <div className={t.className}>The quick brown fox jumps over the lazy dog</div>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Buttons">
        <div className="flex flex-col gap-8">
          <div>
            <div className="mb-3 text-xs uppercase tracking-wide opacity-50">Default</div>
            <div className="flex flex-wrap items-center gap-4">
              {BUTTON_VARIANTS.map((v) => (
                <a key={v} href="#" className={`btn ${v}`}>
                  <span>Let’s talk</span>
                </a>
              ))}
            </div>
          </div>
          <div>
            <div className="mb-3 text-xs uppercase tracking-wide opacity-50">
              Hover (hover each to preview)
            </div>
            <div className="flex flex-wrap items-center gap-4">
              {BUTTON_VARIANTS.map((v) => (
                <a key={v} href="#" className={`btn ${v}`}>
                  <span>Let’s talk</span>
                </a>
              ))}
            </div>
          </div>
        </div>
      </Section>
    </main>
  );
}
